#!/usr/bin/env bash

executionplane --silent docker volume create vcwc_tools_blank__blank_blank_volume
	

executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_tools_blank__blank_blank_volume:/etc/blank ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/tools/blank/_solution/_configuration/volumes/blank_blank_volume/* /etc/blank

