---
version: '3'
services:

# START SERVICE vcwc/tools/blank
  blank:
    image: ${VCW_REGISTRY}vcwc/tools.blank:1.0.0
    environment: []
    command: ['sleep 10000']
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_blank_volume:/etc/blank']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay, ${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${BLANK_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${BLANK_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${BLANK_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/tools/blank

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true },${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_blank_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
