#!/usr/bin/env bash

executionplane-info "EXECUTING CONTROLPLANE REMOVE"

# implementation can be overridden as required by the solution
# the default implementation executes on all components from the top component down
deploy down $@
