#!/usr/bin/env bash

prefix="vcw_module_vcwc_tools_blank__$1"
prefix="vcw_module_vcwc_tools_blank__$1"

executionplane --silent docker container prune --force

if [[ "vcw_module_vcwc_tools_blank__blank_blank_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_vcwc_tools_blank__blank_blank_volume"
		result=$(docker volume ls | grep "vcw_module_vcwc_tools_blank__blank_blank_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
