#!/usr/bin/env bash

prefix="vcw_module_vcwc_tools_blank__$1"
prefix="vcw_module_vcwc_tools_blank__$1"

if [[ "vcw_module_vcwc_tools_blank__blank_blank_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_tools_blank__blank_blank_volume
fi

if [[ "vcw_module_vcwc_tools_blank__blank_blank_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_vcwc_tools_blank__blank_blank_volume:/etc/blank ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/tools/blank/_module/volumes/blank_blank_volume/* /etc/blank
fi
